theme: jekyll-theme-cayman
title: Weakly Supervised Segmentation with<br>Multi-scale Adversarial Attention Gates
description: Gabriele Valvano, Andrea Leo, Sotirios A. Tsaftaris
google_analytics: UA-169250566-1
show_downloads: true
paper_url: www.google.com
code_url: www.google.com
data_download_url: www.google.com
