theme: jekyll-theme-cayman
title: Weakly Supervised Segmentation with Multi-scale Adversarial Attention Gates
description: Gabriele Valvano, Andrea Leo, Sotirios A. Tsaftaris
google_analytics: UA-169250566-1
show_downloads: true
