theme: jekyll-theme-cayman
title: Weakly Supervised Segmentation with <br>Multi-scale Adversarial Attention Gates
description: Gabriele Valvano, Andrea Leo, Sotirios A. Tsaftaris
google_analytics: UA-169250566-1
show_downloads: true
button_home_url: index
button_paper_url: https://arxiv.org/
button_code_url: https://github.com/gvalvano/multiscale-adversarial-attention-gates
button_data_url: pages/data
button_contacts_url: pages/contacts
banner: https://github.com/gvalvano/wss-multiscale-adversarial-attention-gates/blob/master/images/banner.pdf
